apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  volumes:
    - name: maven-repo
      persistentVolumeClaim:
          claimName: maven-repo
  serviceAccount: jenkins
  containers:
    - name: origin
      image: openshift/origin-cli
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "32Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug-v0.15.0
      imagePullPolicy: Always
      command:
        - /busybox/cat
      env:
        - name: PATH
          value: "$PATH:/busybox:/kaniko"
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      tty: true
      securityContext:
          privileged: true
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "2048Mi"
    - name: maven
      image: maven:3.6.3-jdk-8
      command: 
        - "/bin/bash"
        - "-c"
      args: 
        - cat
      tty: true
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "2048Mi"